helius_api_key = ""
birdeye_api_key = ""
use_cached_txns = false
use_cached_named_swaps = false
use_cached_priced_swaps = false
use_token_cache = true
use_jupiter_token_list = true
fifo = true
write_cache_files = false